### ISSUE TITLE
Target add doesn't work on FreeBSD

### ISSUE THREAD

**Issue by rvrignaud** [Tauop/sshGate#12]
Hello,
It seem's that the copy of sshgate's public key on a FreeBSD (7) target doesn't work.
Maybe because ~/.ssh doesn't exist but only /etc/ssh/authorized_keys ?

Thx,

**Comment by Tauop** [comment]
Hi,

That's why sshGate doesn't emit an error but a warning, so that the administrator can install manually the sshkey.

Btw, I have only look and ssh-copy-id community script and make the same operation. ssh-copy-id will not work on system which doesn't use ~/.ssh/authorized keys too.

Do we have to consider this case as an issue ??

Thx for your return ;)

**Comment by Tauop** [comment]
closed, because of lack of proposition/solution.
Just follow the ssh-copy-id community tool behavior.
